name: Fly Deploy
on:
  push:
    paths:
      - server/**

defaults:
  run:
    working-directory: server

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_PROJECT_PATH: ${{ secrets.FLY_PROJECT_PATH }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions@1.3
          with:
            args: "deploy"
